/*
 * This ratpack file was auto generated by 'gigawatt'
 * @author gsus
 * @date 15-06-2017 13.58
 */
import static ratpack.groovy.Groovy.ratpack

ratpack {
	// external file conf
	include 'modules/server-config.groovy'

	// fake business logic module
	include 'modules/business-stub.groovy'
}
