/*
 * This ratpack file was auto generated by 'gigawatt'
 * @author gsus
 * @date 15-06-2017 13.58
 */
// external
import static ratpack.groovy.Groovy.ratpack
// internal

ratpack {
	handlers {
		get {
			render 'This application was auto generated by "gigawatt"'
		}
	}
}
