/*
 * This ratpack file was auto generated by 'gigawatt'
 * @author gsus
 * @date 15-06-2017 13.58
 */
import static ratpack.groovy.Groovy.ratpack
import ratpack.http.MutableHeaders

ratpack {
	handlers {
		all {
			MutableHeaders headers = response.headers
			headers.set('Access-Control-Allow-Origin', '*')
			headers.set('Access-Control-Allow-Methods','GET')
			headers.set('Access-Control-Allow-Headers', 'x-requested-with, origin, content-type, accept')
			next()
		}
	}
}
