/*
 * This ratpack file was auto generated by 'gigawatt'
 * @author gsus
 * @date 15-06-2017 13.58
 *
 * Example conf class
 * ------------------
 * class ApiData {
 *   String key
 *   String url
 * }
 *
 * Corresponding env variables
 * ---------------------------
 * export RATPACK_DATA__API__KEY='123abcd'
 * export RATPACK_DATA__API__URL='https://api.data.com/v2'
 */
// external
import static ratpack.groovy.Groovy.ratpack
// internal
import conf.ApiData

ratpack {
	serverConfig {
		env()
		require("/data/api", ApiData)
	}
}
